python train_gaussamr_router_probe.py \
  --data-root data/SIRST4-ForLiTE \
  --run-dir runs/gaussamr_context_probe_seed42 \
  --seed 42 \
  --train-size 64 \
  --val-size 32 \
  --epochs 10 \
  --max-steps 1000 \
  --lr 1e-3 \
  --init-checkpoint runs/gaussamr_gaussian_probe_seed42/router_best.pt \
  --full-mask-loss \
  --context-refiner \
  --device cpu